import React from 'react'
import { PageHeader, TermsOfUseComponent } from '../components'
import { MainLayout } from '../layouts'

let data = {
  overview: 'Learn+’s mission is to improve lives through learning. We enable anyone anywhere to create and share educational content (instructors) and to access that educational content to learn (students). We consider our marketplace model the best way to offer valuable educational content to our users. We need rules to keep our platform and services safe for you, us, and our student and instructor community. These Terms apply to all your activities on the Learn+ website, the Learn+ mobile applications, our TV applications, our APIs, and other related services (“Services”). If you publish a course on the Learn+ platform, you must also agree to the Instructor Terms. We also provide details regarding our processing of personal data of our students and instructors in our Privacy Policy. If you are using Learn+ as part of your employer’s Learn+ Business learning and development program, you can consult our Learn+ Business Privacy Statement. If you live in the United States or Canada, by agreeing to these Terms, you agree to resolve disputes with Learn+ through binding arbitration (with very limited exceptions, not in court), and you waive certain rights to participate in class actions, as detailed in the Dispute Resolution section.',
  sections: [],
}

data = {
  ...data,
  sections: [
    {
      id: '1',
      title: 'Accounts',
      description: 'You need an account for most activities on our platform. Keep your password somewhere safe, because you’re responsible for all activity associated with your account. If you suspect someone else is using your account, let us know by contacting our Support Team. You must have reached the age of consent for online services in your country to use Learn+. You need an account for most activities on our platform, including to purchase and access content or to submit content for publication. When setting up and maintaining your account, you must provide and continue to provide accurate and complete information, including a valid email address. You have complete responsibility for your account and everything that happens on your account, including for any harm or damage (to us or anyone else) caused by someone using your account without your permission. This means you need to be careful with your password. You may not transfer your account to someone else or use someone else’s account. If you contact us to request access to an account, we will not grant you such access unless you can provide us with the information that we need to prove you are the owner of that account. In the event of the death of a user, the account of that user will be closed. You may not share your account login credentials with anyone else. You are responsible for what happens with your account and Learn+ will not intervene in disputes between students or instructors who have shared account login credentials. You must notify us immediately upon learning that someone else may be using your account without your permission (or if you suspect any other breach of security) by contacting our Support Team. We may request some information from you to confirm that you are indeed the owner of your account. Students and instructors must be at least 18 years of age to create an account on Learn+ and use the Services. If you are younger than 18 but above the required age for consent to use online services where you live (for example, 13 in the US or 16 in Ireland), you may not set up an account, but we encourage you to invite a parent or guardian to open an account and help you access content that is appropriate for you. If you are below this age of consent to use online services, you may not create a Learn+ account. If we discover that you have created an account that violates these rules, we will terminate your account. Under our Instructor Terms, you may be requested to verify your identity before you are authorized to submit content for publication on Learn+. You can terminate your account at any time by following the steps here. Check our Privacy Policy to see what happens when you terminate your account.',
      subsection: [],
    },
    {
      id: '2',
      title: 'Content Enrollment and Lifetime Access',
      description: 'When you enroll in a course or other content, you get a license from us to view it via the Learn+ Services and no other use. Don’t try to transfer or resell content in any way. We generally grant you a lifetime access license, except when we must disable the content because of legal or policy reasons or for enrollments via Subscription Plans. Under our Instructor Terms, when instructors publish content on Learn+, they grant Learn+ a license to offer a license to the content to students. This means that we have the right to sublicense the content to enrolled students. As a student, when you enroll in a course or other content, whether it’s free or paid content, you are getting a license from Learn+ to view the content via the Learn+ platform and Services, and Learn+ is the licensor of record. Content is licensed, and not sold, to you. This license does not give you any right to resell the content in any manner (including by sharing account information with a purchaser or illegally downloading the content and sharing it on torrent sites). In legal, more complete terms, Learn+ grants you (as a student) a limited, non-exclusive, non-transferable license to access and view the content for which you have paid all required fees, solely for your personal, non-commercial, educational purposes through the Services, in accordance with these Terms and any conditions or restrictions associated with the particular content or feature of our Services. All other uses are expressly prohibited. You may not reproduce, redistribute, transmit, assign, sell, broadcast, rent, share, lend, modify, adapt, edit, create derivative works of, sublicense, or otherwise transfer or use any content unless we give you explicit permission to do so in a written agreement signed by a Learn+ authorized representative. This also applies to content you can access via any of our APIs. We generally give a lifetime access license to our students when they enroll in a course or other content. However, we reserve the right to revoke any license to access and use any content at any point in time in the event where we decide or are obligated to disable access to the content due to legal or policy reasons, for example, if the course or other content you enrolled in is the object of a copyright complaint, or if we determine it violates our Trust & Safety Guidelines. This lifetime access license does not apply to enrollments via Subscription Plans or to add-on features and services associated with the course or other content you enroll in. For example, instructors may decide at any time to no longer provide teaching assistance or Q&A services in association with the content. To be clear, the lifetime access is to the course content but not to the instructor. Instructors may not grant licenses to their content to students directly, and any such direct license shall be null and void and a violation of these Terms.',
      subsection: [],
    },
    {
      id: '3',
      title: 'Payments, Credits, and Refunds',
      description: 'When you make a payment, you agree to use a valid payment method. If you aren’t happy with your content, Learn+ offers a 30-day refund or credit for most content purchases.',
      subsection: [
        {
          id: '1',
          title: 'Pricing',
          description: 'The prices of content on Learn+ are determined based on the terms of the Instructor Terms and our Promotions Policy. In some instances, the price of content offered on the Learn+ website may not be exactly the same as the price offered on our mobile or TV applications, due to mobile platform providers’ pricing systems and their policies around implementing sales and promotions. We occasionally run promotions and sales for our content, during which certain content is available at discounted prices for a set period of time. The price applicable to the content will be the price at the time you complete your purchase of the content (at checkout). Any price offered for particular content may also be different when you are logged into your account from the price available to users who aren’t registered or logged in, because some of our promotions are available only to new users. If you are logged into your account, the listed currency you see is based on your location when you created your account. If you are not logged into your account, the price currency is based on the country where you are located. We do not enable users to see pricing in other currencies. If you are a student located in a country where use and sales tax, goods and services tax, or value added tax is applicable to consumer sales, we are responsible for collecting and remitting that tax to the proper tax authorities. Depending on your location, the price you see may include such taxes, or tax may be added at checkout.',
        },
        {
          id: '2',
          title: 'Payments',
          description: 'You agree to pay the fees for content that you purchase, and you authorize us to charge your debit or credit card or process other means of payment (such as Boleto, SEPA, direct debit, or mobile wallet) for those fees. Learn+ works with payment service providers to offer you the most convenient payment methods in your country and to keep your payment information secure. We may update your payment methods using information provided by our payment service providers. Check out our Privacy Policy for more details. When you make a purchase, you agree not to use an invalid or unauthorized payment method. If your payment method fails and you still get access to the content you are enrolling in, you agree to pay us the corresponding fees within thirty (30) days of notification from us. We reserve the right to disable access to any content for which we have not received adequate payment.',
        },
        {
          id: '3',
          title: 'Refunds and Refund Credits',
          description: 'If the content you purchased is not what you were expecting, you can request, within 30 days of your purchase of the content, that Learn+ apply a refund to your account. This refund option does not apply to Subscription Plan purchases, which are covered in Section 8.4 below. We reserve the right to apply your refund as a refund credit or a refund to your original payment method, at our discretion, depending on capabilities of our payment service providers, the platform from which you purchased your content (website, mobile or TV app), and other factors. No refund is due to you if you request it after the 30-day guarantee time limit has passed. However, if the content you previously purchased is disabled for legal or policy reasons, you are entitled to a refund beyond this 30-day limit. Learn+ also reserves the right to refund students beyond the 30-day limit in cases of suspected or confirmed account fraud. To request a refund, follow the steps here. As detailed in the Instructor Terms, instructors agree that students have the right to receive these refunds. If we decide to issue refund credits to your account, they will be automatically applied towards your next content purchase on our website, but can’t be used for purchases in our mobile or TV applications. Refund credits may expire if not used within the specified period and have no cash value, in each case unless otherwise required by applicable law. At our discretion, if we believe you are abusing our refund policy, such as if you’ve consumed a significant portion of the content that you want to refund or if you’ve previously refunded the content, we reserve the right to deny your refund, restrict you from other future refunds, ban your account, and/or restrict all future use of the Services. If we ban your account or disable your access to the content due to your violation of these Terms or our Trust & Safety Guidelines, you will not be eligible to receive a refund. Additional information on our refund policy is available here.',
        },
        {
          id: '4',
          title: 'Gift and Promotional Codes',
          description: 'If the content you purchased is not what you were expecting, you can request, within 30 days of your purchase of the content, that Learn+ apply a refund to your account. This refund option does not apply to Subscription Plan purchases, which are covered in Section 8.4 below. We reserve the right to apply your refund as a refund credit or a refund to your original payment method, at our discretion, depending on capabilities of our payment service providers, the platform from which you purchased your content (website, mobile or TV app), and other factors. No refund is due to you if you request it after the 30-day guarantee time limit has passed. However, if the content you previously purchased is disabled for legal or policy reasons, you are entitled to a refund beyond this 30-day limit. Learn+ also reserves the right to refund students beyond the 30-day limit in cases of suspected or confirmed account fraud. To request a refund, follow the steps here. As detailed in the Instructor Terms, instructors agree that students have the right to receive these refunds. If we decide to issue refund credits to your account, they will be automatically applied towards your next content purchase on our website, but can’t be used for purchases in our mobile or TV applications. Refund credits may expire if not used within the specified period and have no cash value, in each case unless otherwise required by applicable law. At our discretion, if we believe you are abusing our refund policy, such as if you’ve consumed a significant portion of the content that you want to refund or if you’ve previously refunded the content, we reserve the right to deny your refund, restrict you from other future refunds, ban your account, and/or restrict all future use of the Services. If we ban your account or disable your access to the content due to your violation of these Terms or our Trust & Safety Guidelines, you will not be eligible to receive a refund. Additional information on our refund policy is available here.',
        },
      ],
    },
  ],
}
const TermsOfUsePage = () => (
    <>
      <PageHeader title="Learn+ | Terms of Use" />
      <TermsOfUseComponent data={data} />
    </>
)
TermsOfUsePage.getLayout = (page) => (
  <MainLayout>
    {page}
  </MainLayout>
)
export default TermsOfUsePage
