export { isEmail } from './checkIfEmail'
export { isPhone, phoneRegex } from './checkIfPhone'
export { wait } from './await'
export { countryList } from './countries'
export { sign, JWT_SECRET, JWT_EXPIRES_IN, decode, verify } from './jwt'
